export const TEST_TOKEN = process.env.MOCK_TOKEN || null;
export const MOBILE_BOUNDARY = 768;
export const MAX_SQL_SPENT_TIME = 0;
export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_NOTIFICATION_DURATION = 5;

export enum EventKey {
    UNAUTHORIZED = 'UNAUTHORIZED',
    UNCONNECTED = 'UNCONNECTED',
    CONFIRM_SEARCH_ADDRESS = 'CONFIRM_SEARCH_ADDRESS',
    REFRESH_CREATED_LABELS = 'REFRESH_CREATED_LABELS',
    REQUEST_SIGN = 'REQUEST_SIGN',
    SIGN_RESULT = 'SIGN_RESULT',
}

